language: python
python:
  - "2.7"
# command to install dependencies
install:
  - pip install nose pylint
# command to run tests
script:
  echo "TODO: enable later"
  # - find . -name "*.py" | xargs pylint -E
