# https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux_atomic_host/7/html/getting_started_with_kubernetes/get_started_provisioning_storage_in_kubernetes
# check ./volume-mysql-server.yml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mysql001-1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
