apiVersion: v1
kind: Pod
metadata:
  name: hello-mysql-server
spec:
  containers:
  - name: hello-mysql-server
    image: mysql
    ports:
    - containerPort: 3306
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: "my-secret-pw"
    volumeMounts:
    - name: mysql-storage
      mountPath: /var/lib/mysql
      
  volumes:
  - name: mysql-storage
    emptyDir: {}
