---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: my-wordpress-mariadb-backup
spec:
  schedule: "*/1 * * * *"
  # TODO: ideally we need to create daily or weekly backup, instead of every minute
  # schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: my-wordpress-mariadb-backup
            image: mysql
            command: ["/usr/bin/mysqldump", "-ubn_wordpress", "-p8fwWcgBn5V", 
                      "-P3306", "-hmy-wordpress-mariadb",
                      "bitnami_wordpress", "--result-file=/backup/db_backup.sql"]
            volumeMounts:
              - mountPath: /backup
                name: backup
          volumes:
            - name: backup
              persistentVolumeClaim:
                claimName: mariadb-backup
          restartPolicy: OnFailure
