---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: my-wordpress-mariadb-backup
spec:
  schedule: "*/1 * * * *"
  # TODO: ideally we need to create daily or weekly backup, instead of every minute
  # schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: my-wordpress-mariadb-backup
            image: mysql
            command: ["bash", "-ex", "/challenges-kubernetes/Scenario-302/backup_db.sh"]
            volumeMounts:
              - mountPath: /backup
                name: backup
              - mountPath: /challenges-kubernetes
                name: git-volume                
          volumes:
            - name: backup
              persistentVolumeClaim:
                claimName: mariadb-backup
          restartPolicy: OnFailure
            - name: git-volume
              gitRepo:
                repository: "https://github.com/DennyZhang/challenges-kubernetes.git"
